name: test deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Or your preferred runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Setup Node.js environment
        uses: actions/setup-node@v3  # Combined setup for efficiency
        with:
          node-version: 20  # Adjust based on your project's requirements

      - name: Install Angular CLI
        run: npm install -g @angular/cli --force  # Install globally

      - name: Install project dependencies
        run: npm ci  # Use npm ci or yarn install based on your project setup

      - name: Build frontend application
        run: npm run build  # Or your build command

      - name: Build Docker image
        run: docker build -t ${{ secrets.TEST_DOCKER_USERNAME }}/test .

      - name: Login to Docker Hub (securely using a login action)
        uses: docker/login-action@v2  # Use a dedicated action for better security
        with:
          username: ${{ secrets.TEST_DOCKER_USERNAME }}
          password: ${{ secrets.TEST_DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.TEST_DOCKER_USERNAME }}/test

      - name: Deploy to server (secure SSH key deployment)
        uses: nyanhsu/action-ssh-key-deploy@v1.2  # Secure SSH key deployment
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.TEST_USER_NAME }}
          # Avoid referencing secrets directly in the script
          # (action handles secure key deployment)
          key_name: ${{ secrets.TEST_SSH_PRIVATEKEY_NAME }}  # Optional: Name the key

      - name: Docker commands on server (improved error handling)
        run: |
          set -e  # Exit on non-zero exit codes for better error handling

          # SSH connection established by the previous action
          # (key securely transferred)

          # Commands within the script block
          sudo docker login -u ${{ secrets.TEST_DOCKER_USERNAME }} -p ${{ secrets.TEST_DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.TEST_DOCKER_USERNAME }}/test

          # Improved output with better logging
          echo "Starting Docker container..."
          UNIQUE_ID=$(date +%s)
          CONTAINER_NAME="frontend-${UNIQUE_ID}"
          sudo docker run -d --name $CONTAINER_NAME -p 80:80 ${{ secrets.TEST_DOCKER_USERNAME }}/test

          echo "Docker frontend container started: ${CONTAINER_NAME}"


