name: Node Sample Project Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20
          nvm use 20

      - name: Install Dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Create Docker Image
        run: |
          docker build -t ${{ secrets.TEST_DOCKER_USERNAME }}/test .
          docker login -u ${{ secrets.TEST_DOCKER_USERNAME }} -p ${{ secrets.TEST_DOCKER_PASSWORD }}
          docker push ${{ secrets.TEST_DOCKER_USERNAME }}/test

      - name: Setup SSH and SSH to Instance
        run: |
          echo "$TEST_SSH_PRIVATEKEY" > action.pem
          chmod 400 action.pem
          ssh -o StrictHostKeyChecking=no -i action.pem ubuntu@13.53.112.231
          sudo docker login -u ${{ secrets.TEST_DOCKER_USERNAME }} -p ${{ secrets.TEST_DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.TEST_DOCKER_USERNAME }}/test
          echo "Deleting existing container if any"
          UNIQUE_ID=$(date +%s)
          CONTAINER_NAME="practice-${UNIQUE_ID}"
          echo "Starting Docker conta

