name: SSH and Create Folder

on:
  push:
    branches:
      - main

jobs:
  ssh_and_create_folder:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          username: ${{ secrets.TEST_SSH_USERNAME }}
          key: ${{ secrets.TEST_SSH_PRIVATEKEY }}
          script: |
            mkdir -p /root/test
            echo "Folder created successfully in /root/test"


