name: SSH Connection and Folder Creation (Not Recommended for Production)

on:
  push:
    branches: [ main ]

jobs:
  connect_and_create:
    runs-on: ubuntu-latest  # Adjust if you need a different runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SSH Private Key (Not Recommended)
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > temp.pem  # Write the key to a temporary file
          chmod 600 temp.pem  # Set permissions
          ssh -o StrictHostKeyChecking=accept-new -i temp.pem ubuntu@13.53.112.231 \
             mkdir -p /home/ubuntu/test  # Create the folder (if it doesn't exist)
          rm temp.pem  # Delete the temporary file after use


